/*
 * Workspace API
 * Application API used by Workspace Web Edition
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.genesys._internal.workspace.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import com.genesys.workspace.models.KeyValueCollection;

/**
 * VoicecallsidredirectData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-22T16:18:36.606Z")
public class VoicecallsidredirectData {
  @SerializedName("reasons")
  private KeyValueCollection reasons = null;

  @SerializedName("destination")
  private String destination = null;

  @SerializedName("extensions")
  private KeyValueCollection extensions = null;

  public VoicecallsidredirectData reasons(KeyValueCollection reasons) {
    this.reasons = reasons;
    return this;
  }

   /**
   * A key/value pairs list of a data structure that provides additional information associated with this action.
   * @return reasons
  **/
  @ApiModelProperty(value = "A key/value pairs list of a data structure that provides additional information associated with this action.")
  public KeyValueCollection getReasons() {
    return reasons;
  }

  public void setReasons(KeyValueCollection reasons) {
    this.reasons = reasons;
  }

  public VoicecallsidredirectData destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * The other main Directory Number (which your application did not register) involved in this request or event. For instance, the DN of the main party of the call.
   * @return destination
  **/
  @ApiModelProperty(required = true, value = "The other main Directory Number (which your application did not register) involved in this request or event. For instance, the DN of the main party of the call.")
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }

  public VoicecallsidredirectData extensions(KeyValueCollection extensions) {
    this.extensions = extensions;
    return this;
  }

   /**
   * A key/value pairs list of additional data.
   * @return extensions
  **/
  @ApiModelProperty(value = "A key/value pairs list of additional data.")
  public KeyValueCollection getExtensions() {
    return extensions;
  }

  public void setExtensions(KeyValueCollection extensions) {
    this.extensions = extensions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoicecallsidredirectData voicecallsidredirectData = (VoicecallsidredirectData) o;
    return Objects.equals(this.reasons, voicecallsidredirectData.reasons) &&
        Objects.equals(this.destination, voicecallsidredirectData.destination) &&
        Objects.equals(this.extensions, voicecallsidredirectData.extensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reasons, destination, extensions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoicecallsidredirectData {\n");
    
    sb.append("    reasons: ").append(toIndentedString(reasons)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

